language: c

compiler:
    - gcc

before_install:
    - echo $LANG
    - sudo apt-get update
    - sudo apt-get install gfortran

before_script:
    - mkdir build
    - cd build
    - pwd
    - cmake ..

script:
    - $CC --version
    - make
