CC=icc
FC=ifort
CC_LANG_FLAGS=-std=c89
CC_WARN_FLAGS=-Wall -Wextra
CC_OPT_FLAGS=-O3 -ip -parallel
CFLAGS=$(CC_LANG_FLAGS) $(CC_WARN_FLAGS) $(CC_OPT_FLAGS)
FFLAGS=-std90 -warn all -O3
LIBS=-liomp5 -lpthread

